# This configuration file controls the assignment of labels to pull requests
# based on the files that have been changed.
#
# Reference: https://github.com/actions/labeler

'area: web':
  - changed-files:
      - any-glob-to-any-file: 'apps/web/**/*'

'area: admin':
  - changed-files:
      - any-glob-to-any-file: 'apps/admin/**/*'

'area: api':
  - changed-files:
      - any-glob-to-any-file: 'apps/api/**/*'

'area: docs':
  - changed-files:
      - any-glob-to-any-file: '**/*.md'
      - any-glob-to-any-file: 'docs/**/*'

'area: ci':
  - changed-files:
      - any-glob-to-any-file: '.github/**/*'

'area: libs':
  - changed-files:
      - any-glob-to-any-file: 'packages/**/*'
