"area: web":
  - all:
    - changed-files:
      - any-glob-to-any-file: 'apps/web/**/*'

"area: admin":
  - all:
    - changed-files:
      - any-glob-to-any-file: 'apps/admin/**/*'

"area: droid":
  - all:
    - changed-files:
      - any-glob-to-any-file: 'apps/droid/**/*'

"area: core":
  - all:
    - changed-files:
      - any-glob-to-any-file: 'packages/**/*'

"area: ops":
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - '.github/**/*'
        - 'turbo.json'
        - 'package.json'
