area: admin:
  - changed-files:
      - any-glob-to-any-file: 'apps/admin/**/*'

area: droid:
  - changed-files:
      - any-glob-to-any-file: 'apps/droid/**/*'

'area: web':
  - changed-files:
      - any-glob-to-any-file: 'apps/web/**/*'

'area: api':
  - changed-files:
      - any-glob-to-any-file: 'packages/api/**/*'

'area: database':
  - changed-files:
      - any-glob-to-any-file: 'packages/database/**/*'

'area: ui':
  - changed-files:
      - any-glob-to-any-file: 'packages/ui/**/*'

'area: utils':
  - changed-files:
      - any-glob-to-any-file: 'packages/utils/**/*'

'area: docs':
  - changed-files:
      - any-glob-to-any-file: 'docs/**/*'
      - any-glob-to-any-file: '**/*.md'

'area: ci':
  - changed-files:
      - any-glob-to-any-file: '.github/**/*'
