"area: web":
  - changed-files:
      - any-glob-to-any-file: 'apps/web/**/*'

"area: admin":
  - changed-files:
      - any-glob-to-any-file: 'apps/admin/**/*'

"area: droid":
  - changed-files:
      - any-glob-to-any-file: 'apps/droid/**/*'

"area: packages":
  - changed-files:
      - any-glob-to-any-file: 'packages/**/*'

"area: config":
  - changed-files:
      - any-glob-to-any-file: 'packages/config/**/*'
      - any-glob-to-any-file: 'turbo.json'
      - any-glob-to-any-file: 'package.json'
      - any-glob-to-any-file: 'pnpm-lock.yaml'

"area: ci":
  - changed-files:
      - any-glob-to-any-file: '.github/**/*'
