name: Android

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_GOOGLE_SERVICES_BASE64: ${{ secrets.ANDROID_GOOGLE_SERVICES_BASE64 }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm globally
        run: npm install -g pnpm

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: '10'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Mobile Web
        env:
          SKIP_ENV_VALIDATION: "true"
          NEXT_PUBLIC_SITE_URL: "https://mock.com"
        run: cd apps/web && pnpm build:mobile

      - name: Restore Secrets
        run: cd apps/web && pnpm secrets:restore

      - name: Sync Capacitor
        run: cd apps/web && npx cap sync android

      - name: Build APK
        run: |
          cd apps/web/android && ./gradlew assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: apps/web/android/app/build/outputs/apk/debug/app-debug.apk
