name: Label
on: pull_request_target

jobs:
  label:
    name: Label PRs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/labeler@v6
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
